apiVersion: v1
kind: Secret
metadata:
  name: keys
data:
  cmd-import-age: IyBjcmVhdGVkOiAyMDIwLTA3LTE4VDAzOjE2OjQ3LTA3OjAwCiMgcHVibGljIGtleTogYWdlMXl0M3RmcWxmcndkd3gwejB5bndwbGNyNnF4Y3hmYXF5Y3VwcnBteTg5bnI4M2x0eDc0dHFkcHN6bHcKQUdFLVNFQ1JFVC1LRVktMU5KVDVZQ1MyTFdVNFY0UUFKUTZSNEpOVTdMWFBEWDYwMkRaOU5VRkFOVlU1R0RUR1VXQ1E1VDU5TTYK
  age: YWdlMXl0M3RmcWxmcndkd3gwejB5bndwbGNyNnF4Y3hmYXF5Y3VwcnBteTg5bnI4M2x0eDc0dHFkcHN6bHcK
